dist: trusty
sudo: false  # Use the new travis docker based infrastructure

# We always want to be able to reach a tagged version in `git describe`

git:
  depth: 99999

language: python

python:
- '3.6'

services:
  - mongodb

before_install:
- travis_retry pip install --upgrade pip
- travis_retry pip install --progress-bar off coveralls codecov
- travis_retry pip install --progress-bar off --requirement requirements-test.txt


install:
- travis_retry pip install .[test] --upgrade
- pip freeze

script:
- pytest tests integration_tests

after_success:
- coveralls